# fish completion for discvault
complete -c discvault -s h -l help -d "show this help message and exit"
complete -c discvault -s d -l device -r -d "CD device (default: auto-detect)"
complete -c discvault -s o -l base-dir -r -d "Library base directory (overrides config)"
complete -c discvault -l work-dir -r -d "Temporary work directory (overrides config)"
complete -c discvault -l tracks -r -d "Track selection, e.g. 1-10 or 1,2,4-9"
complete -c discvault -l metadata-file -r -d "Import metadata from a .cue, .toc, .json, or .toml file"
complete -c discvault -l metadata-url -l bandcamp-url -r -d "Import metadata from a supported page URL (currently Bandcamp albums)"
complete -c discvault -l artist -r -d "Artist name (overrides metadata lookup)"
complete -c discvault -l album -r -d "Album name (overrides metadata lookup)"
complete -c discvault -l year -r -d "Album year (overrides metadata lookup)"
complete -c discvault -l skip-metadata -d "Proceed without metadata lookup"
complete -c discvault -l strict-manual-fallback -d "Confirm before falling back to manual entry when lookup fails"
complete -c discvault -l metadata-timeout -r -d "Metadata lookup timeout in seconds (overrides config)"
complete -c discvault -l metadata-debug -d "Print metadata provider debug output"
complete -c discvault -l cli -d "Force plain text CLI (default: TUI when interactive)"
complete -c discvault -l check-deps -d "Check helper-tool dependencies for the current selection and exit"
complete -c discvault -l no-flac -d "Skip FLAC encoding"
complete -c discvault -l no-mp3 -d "Skip MP3 encoding"
complete -c discvault -l ogg -d "Enable OGG Vorbis encoding (requires oggenc)"
complete -c discvault -l opus -d "Enable Opus encoding (requires opusenc)"
complete -c discvault -l alac -d "Enable ALAC encoding (requires ffmpeg)"
complete -c discvault -l aac -d "Enable AAC/M4A encoding (requires ffmpeg)"
complete -c discvault -l wav -d "Save final WAV copies in the library"
complete -c discvault -l no-verify -d "Skip FLAC --verify (faster but no integrity check)"
complete -c discvault -l flac-compression -r -d "FLAC compression level 0–8 (default: 8)"
complete -c discvault -l mp3-quality -r -d "lame -V quality for VBR 0–9 (used when --mp3-bitrate=0)"
complete -c discvault -l mp3-bitrate -r -d "lame CBR bitrate (default: 320; set 0 for VBR)"
complete -c discvault -l opus-bitrate -r -d "Opus bitrate in kbps (default: config value)"
complete -c discvault -l aac-bitrate -r -d "AAC bitrate in kbps (default: config value)"
complete -c discvault -l no-image -d "Skip full disc image (cdrdao)"
complete -c discvault -l iso -d "Also export an ISO when the disc has a supported data track"
complete -c discvault -l cdrdao-driver -r -d "cdrdao driver override"
complete -c discvault -l sample-offset -r -d "cdparanoia sample offset correction (overrides config)"
complete -c discvault -l accuraterip -d "Enable optional AccurateRip verification if a helper is installed"
complete -c discvault -l no-accuraterip -d "Disable AccurateRip verification even if enabled in config"
complete -c discvault -l no-cover-art -d "Disable downloading cover art"
complete -c discvault -l keep-wav -d "Keep intermediate WAV files"
complete -c discvault -l eject -d "Eject disc when done"
complete -c discvault -l dry-run -d "Show what would be done without accessing the disc"
complete -c discvault -l debug -d "Print subprocess commands and verbose output"
complete -c discvault -l version -d "show program's version number and exit"
